import { useEffect, useMemo, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { CalendarDays, Clock3, MapPin, Scissors, UserRound } from "lucide-react";
import { useAuth } from "../context/AuthContext";
import { useBusiness } from "../context/BusinessContext";
import { ensureGuestCustomer } from "../services/auth";
import { getActiveBarbers, getActiveServices } from "../services/data";
import { createBooking, getAvailableSlots } from "../services/booking";
import type { Barber, Service } from "../types";
import { ErrorBox, Loading } from "../components";
import { todayKey } from "../lib/date";

export default function Booking(){
 const {profile}=useAuth(); const {business,branches,selectedBranchId,setSelectedBranchId}=useBusiness(); const nav=useNavigate(); const [params]=useSearchParams();
 const [services,setServices]=useState<Service[]>([]),[barbers,setBarbers]=useState<Barber[]>([]),[selectedIds,setSelectedIds]=useState<string[]>([]),[barberId,setBarberId]=useState("any"),[date,setDate]=useState(todayKey(business.timezone||"Asia/Jakarta")),[time,setTime]=useState(""),[name,setName]=useState(profile?.name||""),[phone,setPhone]=useState(profile?.phone||""),[notes,setNotes]=useState(""),[slots,setSlots]=useState<string[]>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const branchId=selectedBranchId;
 useEffect(()=>{const requested=params.get("branch");if(requested&&branches.some(b=>b.id===requested))setSelectedBranchId(requested)},[params,branches]);
 useEffect(()=>{Promise.all([getActiveServices(),getActiveBarbers()]).then(([s,b])=>{const branchServices=s.filter(x=>!x.branchId||x.branchId===branchId);setServices(branchServices);setBarbers(b.filter(x=>x.active&&(!x.branchId||x.branchId===branchId)));setSelectedIds(prev=>prev.filter(id=>branchServices.some(x=>x.id===id)).length?prev.filter(id=>branchServices.some(x=>x.id===id)):(branchServices[0]?[branchServices[0].id]:[]))}).catch(e=>setError(e instanceof Error?e.message:"Gagal memuat data booking.")).finally(()=>setLoading(false))},[branchId]);
 const selectedServices=useMemo(()=>services.filter(s=>selectedIds.includes(s.id)),[services,selectedIds]);
 const totalDuration=selectedServices.reduce((sum,s)=>sum+s.durationMinutes,0); const totalPrice=selectedServices.reduce((sum,s)=>sum+s.price,0);
 const barber=useMemo(()=>barbers.find(x=>x.id===barberId),[barbers,barberId]);
 const combinedService=useMemo<Service|undefined>(()=>selectedServices.length?{...selectedServices[0],name:selectedServices.map(s=>s.name).join(" + "),durationMinutes:totalDuration,price:totalPrice}:undefined,[selectedServices,totalDuration,totalPrice]);
 useEffect(()=>{if(!combinedService||!date)return;setTime("");setError("");if(barberId==="any"){Promise.all(barbers.map(b=>getAvailableSlots(b,combinedService,date))).then(all=>setSlots([...new Set(all.flat())].sort())).catch(e=>setError(e instanceof Error?e.message:"Gagal memuat slot."));return;}if(!barber){setSlots([]);return;}getAvailableSlots(barber,combinedService,date).then(setSlots).catch(e=>setError(e instanceof Error?e.message:"Gagal memuat slot."))},[combinedService?.id,combinedService?.durationMinutes,combinedService?.price,barber?.id,barberId,date,barbers]);
 function toggleService(id:string){setSelectedIds(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id])}
 async function submit(){if(!branchId){setError("Pilih cabang terlebih dahulu.");return}if(!selectedServices.length||!time){setError("Pilih minimal satu layanan dan jam.");return}if(!name.trim()||!phone.trim()){setError("Nama dan nomor WhatsApp diperlukan.");return}setBusy(true);setError("");try{const customer=profile??await ensureGuestCustomer(name.trim(),phone.trim());const result=await createBooking({customerId:customer.uid,customerName:name.trim(),customerPhone:phone.trim(),branchId,barber:barberId==="any"?undefined:barber,services:selectedServices,date,startTime:time,notes});nav(`/booking/success/${result.id}?code=${encodeURIComponent(result.code)}&queue=${result.queueNumber}`)}catch(e){setError(e instanceof Error?e.message:"Booking gagal.")}finally{setBusy(false)}}
 if(loading)return <Loading/>;
 return <div className="container narrow booking-page"><div className="eyebrow">ONLINE BOOKING</div><h1>Atur jadwalmu.</h1><p className="lead">Pilih cabang, satu atau beberapa layanan, barber, tanggal, dan jam yang tersedia.</p>{error&&<ErrorBox message={error}/>}<div className="booking-grid">
 <section className="panel"><h3><MapPin size={18}/> 1. Cabang</h3><div className="choice-grid">{branches.map(b=><button key={b.id} className={`choice ${branchId===b.id?"selected":""}`} onClick={()=>{setSelectedBranchId(b.id);setSelectedIds([]);setBarberId("any");setTime("")}}><b>{b.name}</b><span>{b.address||"Alamat belum diatur"}</span></button>)}</div></section>
 <section className="panel"><h3><Scissors size={18}/> 2. Layanan <small className="muted">({selectedServices.length} dipilih)</small></h3><div className="choice-grid">{services.map(s=><button type="button" key={s.id} className={`choice ${selectedIds.includes(s.id)?"selected":""}`} onClick={()=>toggleService(s.id)}><b>{s.name}</b><span>{s.durationMinutes} menit • {formatIDR(s.price)}</span></button>)}</div></section>
 <section className="panel"><h3><UserRound size={18}/> 3. Barber</h3><div className="choice-grid"><button className={`choice ${barberId==="any"?"selected":""}`} onClick={()=>setBarberId("any")}><b>Barber mana saja</b><span>Sistem memilih barber yang tersedia untuk semua layanan.</span></button>{barbers.map(b=><button key={b.id} className={`choice ${barberId===b.id?"selected":""}`} onClick={()=>setBarberId(b.id)}><b>{b.name}</b><span>{b.specialties?.join(" • ")||b.bio||"Barber profesional"}</span></button>)}</div></section>
 <section className="panel"><h3><CalendarDays size={18}/> 4. Tanggal</h3><input type="date" min={todayKey(business.timezone||"Asia/Jakarta")} value={date} onChange={e=>setDate(e.target.value)}/></section>
 <section className="panel"><h3><Clock3 size={18}/> 5. Jam</h3>{slots.length?<div className="time-grid">{slots.map(t=><button key={t} className={`time ${time===t?"selected":""}`} onClick={()=>setTime(t)}>{t}</button>)}</div>:<div className="empty">{selectedServices.length?"Tidak ada slot tersedia pada kombinasi layanan/barber/tanggal ini.":"Pilih layanan terlebih dahulu."}</div>}</section>
 {!profile&&<section className="panel"><h3>6. Data pelanggan</h3><input placeholder="Nama lengkap" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Nomor WhatsApp" value={phone} onChange={e=>setPhone(e.target.value)}/><small>Login tidak wajib. Akun tamu dibuat otomatis agar booking dapat dilacak.</small></section>}
 <section className="panel"><h3>Catatan</h3><textarea rows={3} placeholder="Opsional, mis. model rambut..." value={notes} onChange={e=>setNotes(e.target.value)}/></section>
 <section className="summary panel"><div><span>Cabang</span><b>{branches.find(b=>b.id===branchId)?.name||"-"}</b></div><div><span>Layanan</span><b>{selectedServices.map(s=>s.name).join(", ")||"-"}</b></div><div><span>Durasi</span><b>{totalDuration?`${totalDuration} menit`:"-"}</b></div><div><span>Barber</span><b>{barberId==="any"?"Barber mana saja":(barber?.name||"-")}</b></div><div><span>Jadwal</span><b>{date} {time||"-"}</b></div><div><span>Total</span><strong>{selectedServices.length?formatIDR(totalPrice):"-"}</strong></div><button className="btn primary big full" disabled={!time||busy||!branchId||!selectedServices.length} onClick={submit}>{busy?"Memproses...":"Konfirmasi Booking"}</button></section>
 </div></div>
}
function formatIDR(v:number){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(v)}
