import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Copy, Tag } from "lucide-react";
import { Empty, ErrorBox, Loading } from "../components";
import { useAuth } from "../context/AuthContext";
import { getPromos, promoIsCurrentlyActive, formatIDR } from "../services/promo";
import { useBusiness } from "../context/BusinessContext";
import type { Promo } from "../types";

export default function CustomerPromos(){const {profile}=useAuth();const {selectedBranchId}=useBusiness();const [items,setItems]=useState<Promo[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");useEffect(()=>{getPromos(true).then(setItems).catch(e=>setError(e instanceof Error?e.message:"Gagal memuat promo.")).finally(()=>setLoading(false))},[]);if(loading)return <Loading/>;const visible=items.filter(p=>!p.branchIds?.length||!selectedBranchId||p.branchIds.includes(selectedBranchId));return <div><div className="customer-hero"><div><div className="eyebrow">PROMO</div><h1>Promo untukmu</h1><p className="lead">Gunakan kode promo saat booking. Promo hanya tersedia untuk akun customer yang login.</p></div><Link className="btn primary" to="/booking">Booking Sekarang</Link></div>{error&&<ErrorBox message={error}/>} {visible.length===0?<Empty>Belum ada promo aktif.</Empty>:<div className="cards">{visible.map(p=><PromoCard key={p.id} promo={p}/>)}</div>}</div>}
function PromoCard({promo}:{promo:Promo}){async function copy(){if(promo.promoCode)await navigator.clipboard?.writeText(promo.promoCode)}return <article className="booking-card"><div className="card-top"><span className="status CONFIRMED"><Tag size={13}/> {promo.discountType==="PERCENTAGE"?`${promo.discountValue}% OFF`:formatIDR(promo.discountValue)}</span><b>{promoIsCurrentlyActive(promo)?"Aktif":"Berakhir"}</b></div><h3>{promo.title}</h3><p>{promo.description||"Promo khusus pelanggan Barber Online."}</p>{promo.minimumTransaction?<div className="meta"><span>Min. transaksi {formatIDR(promo.minimumTransaction)}</span></div>:null}{promo.promoCode&&<div className="card-bottom"><strong>{promo.promoCode}</strong><button className="btn secondary" onClick={copy}><Copy size={15}/> Salin</button></div>}</article>}
