import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Plus, Receipt, RefreshCw } from "lucide-react";
import { Empty, ErrorBox, Loading } from "../components";
import { useAuth } from "../context/AuthContext";
import { useBusiness } from "../context/BusinessContext";
import { getAllBookings } from "../services/data";
import { getProducts } from "../services/inventory";
import { createTransaction, getTransactionForBooking, getTransactions, markTransactionPaid } from "../services/transaction";
import { getActiveServices } from "../services/data";
import type { Booking, Product, Service, Transaction, TransactionItem } from "../types";

const money=(v:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(v);
const methods: NonNullable<Transaction["method"]>[]=["CASH","QRIS","TRANSFER","OTHER"];

export default function Transactions({ barberOnly=false }:{barberOnly?:boolean}){
  const { profile }=useAuth(); const { selectedBranchId }=useBusiness();
  const [items,setItems]=useState<Transaction[]>([]); const [bookings,setBookings]=useState<Booking[]>([]); const [services,setServices]=useState<Service[]>([]); const [products,setProducts]=useState<Product[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const [bookingId,setBookingId]=useState(""); const [barberId,setBarberId]=useState(""); const [method,setMethod]=useState<NonNullable<Transaction["method"]>>("CASH"); const [discount,setDiscount]=useState(0); const [lines,setLines]=useState<TransactionItem[]>([]); const [serviceId,setServiceId]=useState(""); const [productId,setProductId]=useState(""); const [qty,setQty]=useState(1); const [busy,setBusy]=useState(false);
  async function load(){if(!selectedBranchId){setLoading(false);return;} setLoading(true);try{setError("");const [t,b,s,p]=await Promise.all([getTransactions(selectedBranchId,barberOnly?profile?.barberId:undefined),getAllBookings(),getActiveServices(),getProducts(selectedBranchId,true)]);setItems(t);setBookings(b.filter(x=>x.branchId===selectedBranchId));setServices(s.filter(x=>!x.branchId||x.branchId===selectedBranchId));setProducts(p)}catch(e){setError(e instanceof Error?e.message:"Gagal memuat transaksi.")}finally{setLoading(false)}}
  useEffect(()=>{load()},[selectedBranchId,profile?.barberId,barberOnly]);
  const selectedBooking=bookings.find(b=>b.id===bookingId); const subtotal=useMemo(()=>lines.reduce((a,x)=>a+x.subtotal,0),[lines]); const total=Math.max(0,subtotal-Number(discount||0));
  function addService(){const s=services.find(x=>x.id===serviceId);if(!s)return;setLines(v=>[...v,{type:"SERVICE",itemId:s.id,name:s.name,quantity:1,unitPrice:s.price,subtotal:s.price}]);setServiceId("")}
  function addProduct(){const p=products.find(x=>x.id===productId);if(!p)return;const n=Number(qty);if(n<1)return;setLines(v=>[...v,{type:"PRODUCT",itemId:p.id,name:p.name,quantity:n,unitPrice:p.sellingPrice,subtotal:p.sellingPrice*n}]);setProductId("");setQty(1)}
  function removeLine(index:number){setLines(v=>v.filter((_,i)=>i!==index))}
  async function create(){if(!selectedBranchId||!profile||!lines.length)return;setBusy(true);try{let barber=profile.barberId?{id:profile.barberId,name:profile.name}:undefined;if(selectedBooking?.barberId) barber={id:selectedBooking.barberId,name:selectedBooking.barberName||""};await createTransaction({branchId:selectedBranchId,booking:selectedBooking,customerId:selectedBooking?.customerId,customerName:selectedBooking?.customerName,customerPhone:selectedBooking?.customerPhone,barberId:barber?.id,barberName:barber?.name,items:lines,discount,method,createdBy:profile.uid});setBookingId("");setLines([]);setDiscount(0);await load()}catch(e){setError(e instanceof Error?e.message:"Gagal membuat transaksi.")}finally{setBusy(false)}}
  async function chooseBooking(id:string){setBookingId(id); if(!id)return; try{const existing=await getTransactionForBooking(id); if(existing)setError("Booking ini sudah memiliki transaksi. Silakan buka daftar transaksi.");}catch(e){setError(e instanceof Error?e.message:"Gagal memeriksa transaksi booking.")}}
  if(loading)return <Loading/>; if(!selectedBranchId)return <Empty>Pilih cabang terlebih dahulu.</Empty>;
  return <div><div className="section-head"><div><div className="eyebrow">TRANSACTIONS</div><h1>Transaksi</h1><p className="muted">Service + product dalam satu transaksi. Pembayaran Cash, QRIS, Transfer, atau Other.</p></div><button className="btn secondary" onClick={load}><RefreshCw size={16}/> Refresh</button></div>{error&&<ErrorBox message={error}/>}<div className="owner-grid"><section className="panel"><div className="panel-title"><div><div className="eyebrow">NEW TRANSACTION</div><h2>Buat Transaksi</h2></div></div><label>Booking (opsional)<select value={bookingId} onChange={e=>chooseBooking(e.target.value)}><option value="">Walk-in / tanpa booking</option>{bookings.filter(b=>!['CANCELLED','NO_SHOW'].includes(b.status)).map(b=><option key={b.id} value={b.id}>{b.date} {b.startTime} • {b.customerName} • {b.code}</option>)}</select></label><div className="form-grid"><select value={serviceId} onChange={e=>setServiceId(e.target.value)}><option value="">Pilih layanan</option>{services.map(s=><option key={s.id} value={s.id}>{s.name} • {money(s.price)}</option>)}</select><button className="btn secondary" onClick={addService}><Plus size={15}/> Tambah layanan</button><select value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Pilih produk</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} • stok {p.stock} • {money(p.sellingPrice)}</option>)}</select><input type="number" min="1" value={qty} onChange={e=>setQty(Number(e.target.value))}/><button className="btn secondary" onClick={addProduct}><Plus size={15}/> Tambah produk</button></div>{lines.length===0?<Empty>Belum ada item transaksi.</Empty>:<div className="table">{lines.map((x,i)=><div className="table-row" key={`${x.itemId}-${i}`}><div><b>{x.name}</b><small>{x.type} • {x.quantity} × {money(x.unitPrice)}</small></div><strong>{money(x.subtotal)}</strong><button className="btn danger small" onClick={()=>removeLine(i)}>Hapus</button></div>)}</div>}<div className="form-grid"><input type="number" min="0" placeholder="Diskon" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/><select value={method} onChange={e=>setMethod(e.target.value as NonNullable<Transaction["method"]>)}>{methods.map(m=><option key={m}>{m}</option>)}</select></div><div className="checkout-total"><span>Subtotal <b>{money(subtotal)}</b></span><span>Diskon <b>-{money(discount)}</b></span><strong>Total {money(total)}</strong></div><button className="btn primary full" disabled={busy||!lines.length} onClick={create}><Receipt size={16}/>{busy?"Menyimpan...":"Finalisasi Transaksi"}</button></section><section className="panel"><div className="panel-title"><div><div className="eyebrow">RECENT</div><h2>Transaksi Terbaru</h2></div></div>{items.length===0?<Empty>Belum ada transaksi.</Empty>:<div className="cards">{items.slice(0,30).map(t=><TransactionCard key={t.id} transaction={t} onPaid={async()=>{await markTransactionPaid(t.id,"CASH");await load()}}/>)}</div>}</section></div></div>;
}
function TransactionCard({transaction:t,onPaid}:{transaction:Transaction;onPaid:()=>Promise<void>}){return <div className="mini-card"><div className="avatar"><CheckCircle2 size={17}/></div><div className="grow"><b>{t.customerName||"Walk-in"}</b><span>{t.items?.map(x=>`${x.name} ×${x.quantity}`).join(", ")||"-"}</span><p>{money(t.total)} • {t.method||t.paymentMethod||"-"}</p><small>{t.status}</small></div>{t.status!=="PAID"&&<button className="btn small primary" onClick={onPaid}>Tandai Lunas</button>}</div>}
